name: devsecops-lite
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  secrets_gitleaks:
    name: Secrets scanning - Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks.sarif --redact
      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

  deps_trivy_fs:
    name: Dependency scan - Trivy (filesystem)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          format: sarif
          output: trivy.sarif
          ignore-unfixed: true
          severity: CRITICAL,HIGH
      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

  iac_checkov:
    name: IaC scan - Checkov (Terraform)
    runs-on: ubuntu-latest
    if: ${{ hashFiles('**/*.tf') != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: sarif
          output_file_path: checkov.sarif
      - name: Upload SARIF to Security tab
        if: ${{ hashFiles('**/*.tf') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

  dast_zap_baseline:
    name: DAST - OWASP ZAP Baseline
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && secrets.DEMO_URL != '' }}
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ secrets.DEMO_URL }}
          cmd_options: "-a -m 5"
